# Generated by Django 2.2.6 on 2021-04-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210403_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выобор картинки', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
